### ISSUE TITLE
Explore Our Range, Fulfilling Potential through Technology and Infrastructure Solutions part will be handle by Pavan kalyan

### ISSUE THREAD

**Issue by Sahilz9** [Sahilz9/Construct-week-b35#3]

**Comment by Sahilz9** [comment]
- [x] While hovering upon the cards the scale size of the card (width & height) should be more than the previous card
- [x] Also hovering upon the button it should change the background and text colour 
- [x] Explore Our Range, Fulfilling Potential through Technology and Infrastructure Solutions part Should be fully responsive.

**Comment by PKalyanReddy** [comment]
I have done the task given to me u

**Comment by Sahilz9** [comment]
Day 2 tasks completed
